services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: label-studio
    ports:
      - "8080:8080"
    environment:
      - LABEL_STUDIO_USERNAME=${LABEL_STUDIO_USERNAME}
      - LABEL_STUDIO_PASSWORD=${LABEL_STUDIO_PASSWORD}
      # - LABEL_STUDIO_USER_TOKEN=${LABEL_STUDIO_USER_TOKEN}
      # Allow all hosts (simplify for dynamic ngrok URL) and trust ngrok domains for CSRF
      - ALLOWED_HOSTS=*
      - DJANGO_ALLOWED_HOSTS=*
      - CSRF_TRUSTED_ORIGINS=https://*.ngrok-free.app,https://*.ngrok.io
    volumes:
      - label-studio-data:/label-studio/data
    restart: unless-stopped
    networks:
      - datannotator-network

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
      - NGROK_REGION=${NGROK_REGION:-us}
    # Rewrite host header so backend sees 'label-studio' while preserving HTTPS at edge
    command: "http --host-header=rewrite label-studio:8080"
    ports:
      - "4040:4040"  # ngrok web interface
    depends_on:
      - label-studio
    restart: unless-stopped
    networks:
      - datannotator-network

volumes:
  label-studio-data:
    driver: local

networks:
  datannotator-network:
    driver: bridge